version: "3.8"

services:
  # Backend API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: job-autofill-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/jobautofill
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - job-autofill-network
    volumes:
      - ./backend/logs:/app/backend/logs
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MongoDB Database
  mongo:
    image: mongo:6.0-focal
    container_name: job-autofill-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=jobautofill
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - job-autofill-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: job-autofill-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - job-autofill-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development API Service (with hot reload)
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: job-autofill-api-dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/jobautofill_dev
    ports:
      - "3001:3000"
      - "9229:9229" # Debug port
    depends_on:
      - mongo
      - redis
    networks:
      - job-autofill-network
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./backend/logs:/app/backend/logs
    profiles:
      - dev

networks:
  job-autofill-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
